### PR TITLE
fixes for Glacier Service

### PR DESCRIPTION
**Pull request by jonnymacs**
- update core with fix to properly serialize the payloadPath objects as json
- add GlacierMiddleware to add apiVersion header, and treeHash checksum headers
- update core nio, and nio-ssl

### CODE REVIEW

**Comment by jonnymacs** [comment]
@adam-fowler if you have a chance to test this branch I'd be grateful. This should resolve #98 and #99. 

I also added support for the glacier treeHash checksum so it should not required as input for apis that require it. Not sure if you were needing this or not, but I saw it in the docs and decided to add it

**Comment by adam-fowler** [comment]
Hi Jonathan,

I’m quite busy at the moment so not sure when I’ll get a chance to check
this out. Should be able to before the end of next week though.

Adam

**Comment by adam-fowler** [comment]
Ran the code and it all looks good. The tree hash stuff is probably unnecessary as when it is required a local copy is usually kept. For instance when I do a multipart upload of an archive I need to keep a copy of the tree hash for each part of the archive, so I can construct a tree hash for the full archive which is sent in the completeMultipartUpload() call.

**Comment by jonnymacs** [comment]
🙌

re the tree hash - I'll leave it in there if it doesn't hurt anything since I see the header is added in other sdks (ruby, go)

**Comment by adam-fowler** [comment]
Yeah sounds good

**Pull request merged**
