### PR TITLE
README updates for 5.x.x

### PR DESCRIPTION
**Pull request by eneko**
Currently when importing this package from the `5.x.x` branch, Swift Package manager is reporting this error:
> .../Package.swift: declared name 'AWSSDKSwift' for package dependency 'https://github.com/swift-aws/aws-sdk-swift.git' does not match the actual package name 'aws-sdk-swift'

I've updated `README` instructions to reflect the correct package name. In addition, I've updated the module names, which are now prefixed with "AWS".

### CODE REVIEW

**Comment by adam-fowler** [comment]
I've been doing v5 documentation changes on the `5.x.x-docs` branch. The `main` branch is where all development is done, but I didn't want to make doc changes for v5 on the main branch as this is the documentation that everyone sees and most people are probably still using v4.

**Comment by eneko** [comment]
Should I go ahead and close the PR or change the base branch?

**Comment by adam-fowler** [comment]
Yeah you can close. If you want to checkout the 5.x.x-docs as well go ahead. I intend to extend the docs this time. You can see I have added a whole page on CredentialProviders as a starting point. 

Thanks for your input.

**Comment by adam-fowler** [comment]
Just verified the docs on 5.x.x docs have the correct setup for Package.swift, so yeah you can close

**Comment by eneko** [comment]
Thanks!

**Pull request closed without merging**
