### PR TITLE
Use upstream docker image for testing

### PR DESCRIPTION
**Pull request by Yasumoto**
This is for #126

### CODE REVIEW

**Comment by adam-fowler** [comment]
You removed the fakes3 and dynamodb-local. Did you mean to do that?

**Comment by jonnymacs** [comment]
@Yasumoto working on a tag today. update on this?

**Comment by adam-fowler** [comment]
We gonna kill this one now?

**Comment by adam-fowler** [comment]
As this work has already been done elsewhere I’m deleting this PR

**Comment by Yasumoto** [comment]
Thank you!

**Pull request closed without merging**
