### PR TITLE
Codify instructions for patching service files.

### PR DESCRIPTION
**Pull request by Yasumoto**
This is thanks to [Adam's excellent writeup](https://github.com/swift-aws/aws-sdk-swift/issues/212#issuecomment-569740068).

### CODE REVIEW

**Comment by adam-fowler** [comment]
Hey Joe, good to hear from you again. I was thinking of doing the same but thought as it was getting a little long we should possibly move the contributing section to a CONTRIBUTING.md file.

**Comment by Yasumoto** [comment]
Thanks! Great to have a more balanced schedule again 😅

Kickass idea, happy to either close this if you’ve started, or take a swing tomorrow (pacific time)!

**Comment by adam-fowler** [comment]
I hadn’t started. I’ll let you do it. :-)

**Comment by Yasumoto** [comment]
I just moved this over, but I'm still percolating on a better and/or more comprehensive doc now that it has more room. Might be better in a separate PR tho.

**Comment by adam-fowler** [comment]
Lets commit this one and talk about future changes. By more comprehensive doc, do you mean the readme or contributing?

**Comment by Yasumoto** [comment]
I was thinking something about `CONTRIBUTING`, but still thinking about if there's really much that'd be necessary in addition to your current writeup.

**Pull request merged**
